name: CI HealthTrack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libxss1 libgtk-3-0
        wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64 /opt/google/chrome
        sudo ln -s /opt/google/chrome/chrome /usr/bin/google-chrome

        wget https://storage.googleapis.com/chrome-for-testing-public/124.0.6367.91/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run unit and functional tests
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 &  # Requerido por Selenium headless
        mvn test

    - name: Upload JUnit test reports
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-reports
        path: target/surefire-reports

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz

    - name: Run JMeter performance test
      run: |
        apache-jmeter-5.6.3/bin/jmeter -n \
          -t src/test/java/com/healthtrack/HealthTrackTestPlan.jmx \
          -l results.jtl

    - name: Generate JMeter HTML Report
      run: |
        mkdir jmeter-report
        apache-jmeter-5.6.3/bin/jmeter -g results.jtl -o jmeter-report

    - name: Upload JMeter HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-html-report
        path: jmeter-report

    - name: Notify on failure (example only)
      if: failure()
      run: echo "El pipeline falló. Revisa los reportes en GitHub Actions."
